### ISSUE TITLE
App crashing after update sdk 6.1.0

### ISSUE THREAD

**Issue by DivyeshTarsariya** [fbsamples/audience-network#126]
### version : 6.1.0

Fatal Exception: java.lang.RuntimeException: Unable to start activity ### ComponentInfo{}: **android.os.BadParcelableException: ClassNotFoundException when unmarshalling:** com.facebook.ads.internal.androidx.support.v7.widget.RecyclerView$SavedState
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by ashaevy** [comment]
Fixed in 6.2.0
