### ISSUE TITLE
onContentProviderCreated(android.content.Context)

### ISSUE THREAD

**Issue by fmanoir** [fbsamples/audience-network#138]
java.lang.AbstractMethodError: abstract method "void com.facebook.ads.internal.api.AudienceNetworkAdsApi.onContentProviderCreated(android.content.Context)"
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.doCallInitialize(DynamicLoaderFactory.java:160)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.access$200(DynamicLoaderFactory.java:41)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:122)
        at java.lang.Thread.run(Thread.java:919)

**Comment by ParthCorepix** [comment]
@fmanoir  any solution for this error?

**Comment by fmanoir** [comment]
Remove AudienceNetwork.dex
