### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from null array

### ISSUE THREAD

**Issue by appsapiconsole** [fbsamples/audience-network#147]
Fatal Exception: java.lang.NullPointerException: Attempt to read from null array
       at com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl.createAudienceNetworkAdsApi(DynamicLoaderImpl.java:137)
       at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.doCallInitialize(DynamicLoaderFactory.java:159)
       at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.access$200(DynamicLoaderFactory.java:41)
       at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:121)
       at java.lang.Thread.run(Thread.java:818)
![image](https://user-images.githubusercontent.com/56867915/116203834-8e83e780-a755-11eb-8187-713efaea9335.png)
![image](https://user-images.githubusercontent.com/56867915/116203917-a3607b00-a755-11eb-9751-9e20b02b473a.png)

**Comment by onur-simsek** [comment]
Hi,
If you are still having this issue, can you use the bug report (https://developers.facebook.com/support/bugs/) tool to report this?

**Comment by francescogatto** [comment]
Same errore here
