### ISSUE TITLE
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/ads/internal/api/Repairable;

### ISSUE THREAD

**Issue by IhaYarre** [fbsamples/audience-network#148]
**java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/ads/internal/api/Repairable;**
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:296)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:289)
        at dalvik.system.DexPathList.findClass(DexPathList.java:418)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.newInstance(Native Method)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.doMakeLoader(DynamicLoaderFactory.java:222)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.access$000(DynamicLoaderFactory.java:41)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:101)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.ads.internal.api.Repairable" on path: DexPathList[[dex file "/data/user/0/com.ppop.keys/files/audience_network.dex"],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at dalvik.system.DexFile.defineClassNative(Native Method) 
        at dalvik.system.DexFile.defineClass(DexFile.java:296) 
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:289) 
        at dalvik.system.DexPathList.findClass(DexPathList.java:418) 
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54) 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380) 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312) 
        at java.lang.Class.newInstance(Native Method) 
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.doMakeLoader(DynamicLoaderFactory.java:222) 
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.access$000(DynamicLoaderFactory.java:41) 
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:101) 
        at java.lang.Thread.run(Thread.java:761)

**Comment by onur-simsek** [comment]
Hi, 
If you are still having this issue, can you use the bug report (https://developers.facebook.com/support/bugs/) tool to report this?
