### ISSUE TITLE
Crash when show interstitial very much. 

### ISSUE THREAD

**Issue by Dukichtre93** [fbsamples/audience-network#42]
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.facebook.ads.internal.view.d.b.i$2.a(Unknown Source)
       at com.facebook.ads.internal.view.d.b.i$2.a(Unknown Source)
       at com.facebook.ads.internal.g.r.b(Unknown Source)
       at com.facebook.ads.internal.g.r.a(Unknown Source)
       at com.facebook.ads.internal.view.o$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5651)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by ljwan12** [comment]
same with me,so many crash

**Comment by phzhou** [comment]
Hi @Dukichtre93 and @ljwan12 
There is a known issue in the 4.25 version of the SDK, at some cases there would be a racing condition causing this "divide by zero" crash. This will be fixed in the 4.26 version which will be published in a few days, or at the same time you can revert back to a more stable version of 4.23 before 4.26 is published.
Thanks!

**Comment by dat0106** [comment]
...
