### ISSUE TITLE
Crash when i show rewardedVideo

### ISSUE THREAD

**Issue by lizhiwei92** [fbsamples/audience-network#47]
1. Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.ads.internal.util.af.a(android.view.MotionEvent, android.view.View, android.view.View)' on a null object reference
	at com.facebook.ads.internal.view.l$1.a(Unknown Source)
	at com.facebook.ads.internal.view.l$1.a(Unknown Source)
	at com.facebook.ads.internal.g.r.b(Unknown Source)
	at com.facebook.ads.internal.g.r.a(Unknown Source)
	at com.facebook.ads.internal.view.n.a(Unknown Source)
	at com.facebook.ads.internal.view.d.c.b.setVideoState(Unknown Source)
	at com.facebook.ads.internal.view.d.c.b.onCompletion(Unknown Source)

2.Crash when i show rewardedVideo, while i post run on uiThread
Caused by: java.lang.IllegalStateException: ad already started
	at com.facebook.ads.internal.DisplayAdController.c(Unknown Source)
	at com.facebook.ads.RewardedVideoAd.show(Unknown Source)
	at com.superpow.wordchef.ad.c.a$2$3.run(RewardAdManager.java:149)
	at android.os.Handler.handleCallback(Handler.java:751)

**Comment by lizhiwei92** [comment]
by the way, the sdk version is 4.23

**Comment by phzhou** [comment]
Hi @lizhiwei92 have you tried to reproduce the issues with a newer version of the SDK?

**Comment by phzhou** [comment]
Closing. Feel free to open again if the issue still exists. Thanks!
