### ISSUE TITLE
SDK crashes with CalledFromWrongThreadException while playing an instream ad

### ISSUE THREAD

**Issue by kumarbanty** [fbsamples/audience-network#53]
# Crash logs
Fatal Exception: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6728)
       at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1028)
       at android.view.ViewGroup.invalidateChild(ViewGroup.java:4716)
       at android.view.View.invalidateInternal(View.java:11820)
       at android.view.View.invalidate(View.java:11784)
       at android.view.View.invalidateParentIfNeeded(View.java:11973)
       at android.view.View.clearAnimation(View.java:17903)
       at com.facebook.ads.internal.view.d.b.d$1.a(Unknown Source)
       at com.facebook.ads.internal.view.d.b.d$1.a(Unknown Source)
       at com.facebook.ads.internal.g.r.b(Unknown Source)
       at com.facebook.ads.internal.g.r.a(Unknown Source)
       at com.facebook.ads.internal.view.o.a(Unknown Source)
       at com.facebook.ads.internal.view.d.c.b.setVideoState(Unknown Source)
       at com.facebook.ads.internal.view.d.c.b.a(Unknown Source)
       at com.facebook.ads.internal.view.o.a(Unknown Source)
       at com.facebook.ads.internal.view.d.b.b$3$1.onAudioFocusChange(Unknown Source)
       at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:2526)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:160)

**Comment by phzhou** [comment]
Hi @kumarbanty!
As the error message suggested, did you create the view for in-stream video and manipulate the view on the same thread?

If you don't mind posting code snippet showing how you are creating the view and using it that would be helpful to identify the issue

**Comment by phzhou** [comment]
Closing. Feel free to open again if there is still issue! Thanks!

**Comment by bantyK** [comment]
Hello @phzhou this crash is still happening and that too in a large number, have a look our fabric link for this crash 

https://fabric.io/vuclip4/android/apps/com.vuclip.viu/issues/5adac71f36c7b2352789910d?time=last-twenty-four-hours

Can you help us on how we can fix this crash or atleast gracefully handle this so that the app does not crash abruptly.
