### ISSUE TITLE
Does audience network android sdk require android min api level to 17 ?

### ISSUE THREAD

**Issue by nottoobad** [fbsamples/audience-network#54]
Crashed when showing interstitial ads on android 4.1.1.
Audience network android sdk version is 4.23.0.
View.generateViewId only available via android api level 17.
Fatal Exception: java.lang.NoSuchMethodError: android.view.View.generateViewId
       at com.facebook.ads.internal.adapters.k.a(Unknown Source)
       at com.facebook.ads.internal.adapters.i.a(Unknown Source)
       at com.facebook.ads.internal.adapters.i.a(Unknown Source)
       at com.facebook.ads.internal.adapters.j.loadInterstitialAd(Unknown Source)
       at com.facebook.ads.internal.DisplayAdController.a(Unknown Source)
       at com.facebook.ads.internal.DisplayAdController.o(Unknown Source)
       at com.facebook.ads.internal.DisplayAdController.d(Unknown Source)
       at com.facebook.ads.internal.DisplayAdController$5.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Method.java)

**Comment by phzhou** [comment]
Hi @nottoobad could you try to reproduce the issue with the newer SDK version?

**Comment by phzhou** [comment]
Closing since no activity
