### ISSUE TITLE
Audience network crash

### ISSUE THREAD

**Issue by harshdchandel** [fbsamples/audience-network#59]
Caused by java.lang.RuntimeException: failure code: -32
       at android.media.MediaPlayer.invoke(MediaPlayer.java:729)
       at android.media.MediaPlayer.getInbandTrackInfo(MediaPlayer.java:1893)
       at android.media.MediaPlayer.getTrackInfo(MediaPlayer.java:1870)
       at com.facebook.ads.internal.view.c.c.b.d(Unknown Source)
       at com.facebook.ads.internal.view.u.j(Unknown Source)
       at com.facebook.ads.internal.view.n.setUpContent(Unknown Source)
       at com.facebook.ads.internal.view.n.a(Unknown Source)
       at com.facebook.ads.AudienceNetworkActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:5275)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
       at android.app.ActivityThread.access$800(ActivityThread.java:142)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5118)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by phzhou** [comment]
Hi @harshdchandel could you provide more information on the issue?
Is the issue happening all the time or randomly?
What kind of ad format are you trying to use when encountering this issue?
What is the Audience Network SDK version?
What is the test device and the OS version?

Best case if you could provide a sample that can reproduce this issue that will be really helpful.
Thanks!

**Comment by phzhou** [comment]
Closing due to no activity
