### ISSUE TITLE
5.3.0  Didn't find class "com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl" 

### ISSUE THREAD

**Issue by snail9527** [fbsamples/audience-network#94]
Hi, i was use the audience-network 5.3.0，but it cause some crash by few user. they all in android 5.0 or 6.0
 Here is some logcat

java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.makeLoader(Unknown Source)
    at com.facebook.ads.internal.dynamicloading.a.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    ... 3 more
    Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl" on path: DexPathList[[zip file "/data/app/launcher.pie.launcher-1/base.apk"],nativeLibraryDirectories=[/data/app/launcher.pie.launcher-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        ... 4 more
        Suppressed: java.lang.ClassNotFoundException: com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 5 more
        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
java.lang.ClassNotFoundException: Didn't find class "com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    at com.facebook.ads.internal.dynamicloading.**DynamicLoaderFactory.makeLoader**(Unknown Source)
    at com.facebook.ads.internal.dynamicloading.a.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:818)
    Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl" on path: DexPathList[[zip file "/data/app/launcher.pie.launcher-1/base.apk"],nativeLibraryDirectories=[/data/app/launcher.pie.launcher-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        ... 4 more
        Suppressed: java.lang.ClassNotFoundException: com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 5 more
        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by phzhou** [comment]
Hi @snail9527 thanks for writing in, this looks like a bug, can you use the official bug report channel here
https://developers.facebook.com/support/bugs/
to file a bug report?

Thanks!
